### ISSUE TITLE
tests are not passing

### ISSUE THREAD

**Issue by mihaiav** [bigskysoftware/idiomorph#52]
I'm trying to file several issues along with tests. It seems that currently there are several (4 tests) falling. Is this expected?

```
 1) Bootstrap test
       "before each" hook for "can morph content to content":
     TypeError: Cannot set properties of null (setting 'innerHTML')
      at clearWorkArea (test-utilities.js:43:29)
      at Context.<anonymous> (bootstrap.js:4:9)

  2) Tests to ensure that idiomorph merges properly
       "before each" hook for "morphs text correctly":
     TypeError: Cannot set properties of null (setting 'innerHTML')
      at clearWorkArea (test-utilities.js:43:29)
      at Context.<anonymous> (fidelity.js:4:9)

  3) Core morphing tests
       "before each" hook for "morphs outerHTML as content properly when argument is null":
     TypeError: Cannot set properties of null (setting 'innerHTML')
      at clearWorkArea (test-utilities.js:43:29)
      at Context.<anonymous> (core.js:4:9)

  4) Tests to compare perf with morphdom
       "before each" hook for "HTML5 Elements Sample Page":
     TypeError: Cannot set properties of null (setting 'innerHTML')
      at clearWorkArea (test-utilities.js:43:29)
      at Context.<anonymous> (perf.js:4:9)


```

**Comment by 1cg** [comment]
tests are passing now, release soon
