### ISSUE TITLE
Can't handle document fragments

### ISSUE THREAD

**Issue by mihaiav** [bigskysoftware/idiomorph#53]
I'm trying to morph a document fragment but it seems that for some reasons this fails. I also wrote a test. Am I doing something wrong. The test represents the way my "framework" works(i.e. using document fragments to encapsulate one or more nodes)

 2) Core morphing tests
       can handle document fragments:
     TypeError: Cannot read properties of null (reading 'replaceChild')
      at morphOldNodeTo (file:///Users/x/go/src/github.com/AVML/idiomorph/src/idiomorph.js:135:39)
      at morphNormalizedContent (file:///Users/x/go/src/github.com/AVML/idiomorph/src/idiomorph.js:91:35)
      at Object.morph (file:///Users/x/go/src/github.com/AVML/idiomorph/src/idiomorph.js:53:20)
      at Context.<anonymous> (core.js:465:19)

// test code
https://github.com/bigskysoftware/idiomorph/pull/54

```

   it('can handle document fragments', function()
     {
         let tpl = document.createElement("template");
         tpl.innerHTML = "<div><button>Foo</button><div>";
         let initial = document.adoptNode(tpl.content);
         let initialFirstChild = initial.firstChild;

         tpl = document.createElement("template");
         tpl.innerHTML = "<p>x</p><p>y</p>"
         let replaceWith =  document.adoptNode(tpl.content);
         Idiomorph.morph(initialFirstChild, replaceWith, {});
         initial.outerHTML.should.equal(`<p>x</p><p>y</p>`);
     });

```

**Comment by MichaelWest22** [comment]
```javascript
  it('can handle document fragments', function()
  {
      let tpl = document.createElement("template");
      tpl.innerHTML = "<div><button>Foo</button><div>";
      let initial = document.adoptNode(tpl.content);
      let initialFirstChild = initial.firstChild;

      tpl = document.createElement("template");
      tpl.innerHTML = "<p>x</p><p>y</p>"
      let replaceWith =  document.adoptNode(tpl.content);
      Idiomorph.morph(initialFirstChild, replaceWith, {});
      let initalOuterHTML = '';
      [].forEach.call(initial.children, function(el) { 
        initalOuterHTML += el.outerHTML;
      });
      initalOuterHTML.should.equal(`<p>x</p><p>y</p>`);
  });
```
Found your test had an issue where you can't call outerHTML on a fragment which I fixed above.

Testing this on version 0.3.0 and was able to reproduce your problem.  But when trying on the current release 0.4.0 it no longer produces the problem and morphs with no errors.  however it seems to morph only the first x node into the inital fragment.  But when testing on the current release we are about it do it seems to work fine!  So hopefully when this releases you should be able to retest.

**Comment by botandrose** [comment]
@mihaiav Should be resolved by the latest v0.7.1 release. Reopen if not!
